# 学习python自带的 buildin 函数

In [20]:
# slice function

import numpy as np

def make_batches(size, batch_size):
    nb_batch = int(np.ceil(size/float(batch_size)))
    return [(i*batch_size, min(size, (i+1)*batch_size)) for i in range(0, nb_batch)]

X = np.array([i for i in range(0,100)])
index_array = np.arange(len(X))
np.random.shuffle(index_array)

batch_size = 12
batches = make_batches(len(X), batch_size)
shuffle = True

def fit(batches, shuffle=True):
    for batch_index, (batch_start, batch_end) in enumerate(batches):
        if shuffle:
            batch_ids = index_array[batch_start:batch_end]
        else:
            batch_ids = slice(batch_start, batch_end)
        
#         if batch_index%2 == 0:
        print('batch_ids:\n', batch_ids)
        print('[batch_ids]:\n', X[batch_ids])

fit(batches, shuffle=True)

fit(batches, shuffle=False)        

batch_ids:
 [57 94 14 95 28 46 18 88 87 64 24 51]
[batch_ids]:
 [57 94 14 95 28 46 18 88 87 64 24 51]
batch_ids:
 [67 47 49 39 23 96 35 30 10 93 16 66]
[batch_ids]:
 [67 47 49 39 23 96 35 30 10 93 16 66]
batch_ids:
 [60 90 27 80 63  6 34 38 68 42  5 50]
[batch_ids]:
 [60 90 27 80 63  6 34 38 68 42  5 50]
batch_ids:
 [99 85 77 91 52 58 92 29 33 75 89 56]
[batch_ids]:
 [99 85 77 91 52 58 92 29 33 75 89 56]
batch_ids:
 [15  0 70  7 37 82 21 44 71 45  8  4]
[batch_ids]:
 [15  0 70  7 37 82 21 44 71 45  8  4]
batch_ids:
 [43 55 19 17 20 25 31  1 40 79 36 69]
[batch_ids]:
 [43 55 19 17 20 25 31  1 40 79 36 69]
batch_ids:
 [53 84 13 11 81 86 12 41 65 74 26  3]
[batch_ids]:
 [53 84 13 11 81 86 12 41 65 74 26  3]
batch_ids:
 [62 61 72 78 59 97  9 54 73 76 22 48]
[batch_ids]:
 [62 61 72 78 59 97  9 54 73 76 22 48]
batch_ids:
 [98 83  2 32]
[batch_ids]:
 [98 83  2 32]
batch_ids:
 slice(0, 12, None)
[batch_ids]:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
batch_ids:
 slice(12, 24, None)
[batch_ids]:
 [

In [25]:
a = int(np.ceil(2.1))
a

3