In [1]:
import numpy as np


In [2]:
vector = np.array([1,2,3,4])

In [3]:
print(vector.shape)

(4,)


In [4]:
matrix = np.array([[1,2,3],[4,5,6]])

In [5]:
print(matrix.shape)

(2, 3)


In [6]:
vector.dtype

dtype('int64')

In [7]:
vector.ndim

1

In [8]:
matrix.ndim

2

In [9]:
matrix.size

6

In [10]:
vector.size

4

In [11]:
vector_str = vector.astype(str)

In [12]:
vector.dtype

dtype('int64')

In [13]:
vector_str.dtype

dtype('<U21')

In [14]:
print(vector)

[1 2 3 4]


In [16]:
print(vector.dtype)

int64


In [17]:
matrix = np.array([[1,2],[3,4],[5,6]])

In [18]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
s = matrix.sum(axis=0)

In [20]:
s

array([ 9, 12])

In [22]:
s = matrix.sum(axis=1)
s

array([ 3,  7, 11])

In [23]:
s = sum(matrix[:,0])

In [24]:
s

9

In [36]:
x = np.zeros(shape=(6,))
x

array([0., 0., 0., 0., 0., 0.])

In [38]:
x = np.zeros(shape=(6,1))
x

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [39]:
x = np.zeros(shape=(6,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
x = np.ones(shape=(6,1))
x

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [45]:
x = np.empty(shape=(6,3))
x

array([[ 6.90863006e-310,  6.90863006e-310,  4.67291682e-310],
       [ 1.97626258e-323,  4.67291937e-310,  6.90862150e-310],
       [ 6.90859155e-310, -4.06843680e+023,  0.00000000e+000],
       [ 0.00000000e+000, -2.41436659e-293,  0.00000000e+000],
       [ 0.00000000e+000, -7.09963370e-270,  0.00000000e+000],
       [ 0.00000000e+000, -1.12258809e+187,  0.00000000e+000]])

In [48]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [50]:
k = np.arange(8).reshape(2,2,2)
k

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [51]:
s = k.sum(axis=0)
s

array([[ 4,  6],
       [ 8, 10]])

In [52]:
s = k.sum(axis=1)
s

array([[ 2,  4],
       [10, 12]])

In [53]:
s = k.sum(axis=2)
s

array([[ 1,  5],
       [ 9, 13]])

In [54]:
k = np.arange(8).reshape(2,2,2)
k

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
m = k.transpose(1,2,0)
m

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [57]:
a = 5%10
a

5

In [58]:
x = np.ones(shape=(6,1))
x

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [63]:
x[1]=2
x
type(x[1])
type(x[1][0])

numpy.float64

In [64]:
print('\baaaa')

aaaa


In [69]:
print('\b'*3)




In [72]:
# print(globals())

In [76]:
from array import *
data = array('d',[ 0.9526, -0.246 , -0.8856, 0.5639, 0.2379,0.9104])
data[0]

0.9526